### ISSUE TITLE
Split Functions

### ISSUE THREAD

**Issue by mrinalinigarg** [ram-jayapalan/filesplit#10]
Hello, 

Instead of split_size can we split when we encounter a new function in our program?

Thanks

**Comment by ram-jayapalan** [comment]
Hi, I don't think I understand your question. I might need more details. Nevertheless the split size is required. It can be a function returning positive integer that can be assigned to split size.

**Comment by mrinalinigarg** [comment]
Hey, thanks for getting back to me.

I mean my function doesn't have a fixed size. So I cannot use a split size.

I have a lot of different functions , can I use a keyword  to split these
functions into different files?
