### ISSUE TITLE
NoneType exception when trying to split with newline=True

### ISSUE THREAD

**Issue by srayatcsg** [ram-jayapalan/filesplit#11]
I am trying to split the 5.5GB word vector file glove.840B.300d.txt (downloaded and unzipped from https://nlp.stanford.edu/projects/glove/). This is a text file so I don't want to split lines across files.

The code I have is:

 fs.split(
        file=wordfile,
        split_size=1073741824,
        output_dir=splitfolder,
        callback=split_cb,
        newline=True )

This generates the first split file and then throws the TypeError object of type 'NoneType' has no len(). I also see the second split file with one line in it.

If I remove newline = True the split runs to completion but I have lines split across files.

**Comment by ram-jayapalan** [comment]
Hi @srayatcsg This seems to be a bug that is now fixed. Please update to the latest version to resolve the issue. Thanks.
