### ISSUE TITLE
The library produces infinite number of empty files

### ISSUE THREAD

**Issue by HubUser** [ram-jayapalan/filesplit#12]
If `split_size` is bigger than the size of the initial file the library infinitely produces empty files. The reason is I guess on the line `filesplit.py:40`. `carry_over` is an empty byte string, but it is not `None`.

**Comment by ram-jayapalan** [comment]
Thanks for bringing this to my attention. Yes the carry_over flag seems to be the culprit. This is now fixed. Please upgrade to the latest version v3.02.
