### ISSUE TITLE
Split size not the right size

### ISSUE THREAD

**Issue by Leadhood** [ram-jayapalan/filesplit#13]
Hi!

Thanks for making and publishing this, it is just what I needed! 

If I ask to split a file at "split_size=4292870144" the result of the first part is "4292000000"

My problem is that I need it to be exactly "4292870144" 

Where is this difference coming from ?

**Comment by ram-jayapalan** [comment]
The default buffer size is set to 1MB. But If your split size is less than default buffer size, then your split size will be used as the buffer size. In your case, it is using the default buffer size which will write the next exceeding ~1MB chunk to the next split file. This is for performance gains and to keep it simple. So it will guarantee that a split won't exceed the given size but at the same time there could be few bytes differences and may not split at the exact mark. You could try adjusting your size to counter-effect.

**Comment by Leadhood** [comment]
Ok, thanks for the clarification!
