### ISSUE TITLE
import name 'Filesplit' Error

### ISSUE THREAD

**Issue by aimanmutasem** [ram-jayapalan/filesplit#15]
Hello all, :) 

`! pip install filesplit`

`Requirement already satisfied: filesplit in ./anaconda3/lib/python3.8/site-packages (3.0.2)`

After I have installed Filesplit, I got the below error when trying to create an instance. Any suggestions to fix this issue?

`from fsplit.filesplit import Filesplit`

`ImportError: cannot import name 'Filesplit' from 'fsplit.filesplit' (/home/aiman/anaconda3/lib/python3.8/site-packages/fsplit/filesplit.py)`

Kind regards,
Aiman Solyman

**Comment by ram-jayapalan** [comment]
Hi there,
I'm unable to reproduce the issue. The issue seems to be on your environment. Also check if there is any circular dependency issue in your script or if the name is being referenced elsewhere. Closing this issue as it is related to the working environment.
