### ISSUE TITLE
INFO: Question regarding output_dir parameter.

### ISSUE THREAD

**Issue by SKowshik4614** [ram-jayapalan/filesplit#16]
Hi Team,

The output_dir param in the split method, can this be an S3 location??

Thanks in advance.

Regards,
Santosh

**Comment by ram-jayapalan** [comment]
Hi,
Unfortunately there is no direct way to upload to S3. One way to do this is use the callback function to write your own s3 upload logic.

**Comment by SKowshik4614** [comment]
Sounds good, thank u @ram-jayapalan :)
