### ISSUE TITLE
Feature Request: Configurable file names 

### ISSUE THREAD

**Issue by LulaSvob** [ram-jayapalan/filesplit#17]
It will be great if we can configure the suffix of the file name to be something different than "_". 
For example I have a system that consumes the files and expects the parts to be with a dash "-" i.e. filename-1.ext etc... So now I have to write a script that renames all files after I create them. If I could configure filesplit to put dash instead of underscore that'd save a lot of work.

**Comment by ram-jayapalan** [comment]
The latest version supports `splitdelimiter` property that can be used to change the split character suffix. Please check out the readme file.
