### ISSUE TITLE
Is this guaranteed not to split the file up in the middle of a row?

### ISSUE THREAD

**Issue by ANTGOMEZ** [ram-jayapalan/filesplit#2]
If you run this util on a very large file made up of data rows, is it guaranteed not to split a row in the middle and therefore corrupt the data?

**Comment by ram-jayapalan** [comment]
The splits are determined on a new line character and there shouldn't be
any incomplete line splits happening like in the middle of a row. So either
you get file splits that are not incomplete or you don't get any splits at
all.

**Comment by rajazone** [comment]
I am getting file split with incomplete line. It got split without encountering a new line character

**Comment by ram-jayapalan** [comment]
Hi,
What type of file are you using? Is it a structured file? Is it a Windows
or Unix based machine?

**Comment by rajazone** [comment]
Sorry, it was my editor. It was not cutting the file short. It is all good.
