### ISSUE TITLE
distutils is deprecated in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [ram-jayapalan/filesplit#20]
Ref : https://www.python.org/dev/peps/pep-0632/#migration-advice

`setup` from setuptools can be used.

https://github.com/ram-jayapalan/filesplit/blob/591258a82e9b86e612e4d69bdc11ad0ad00b50ed/setup.py#L1

**Comment by ram-jayapalan** [comment]
The latest version is using setuptools instead of distutils. Thanks for bringing this up.
