### ISSUE TITLE
Got recursion error while splitting huge file

### ISSUE THREAD

**Issue by boskuv** [ram-jayapalan/filesplit#23]
Got "maximum recursion depth exceeded while calling a Python object" while splitting 8 GB file with bylinecount argument = 100000
Anybody have ideas about it?

**Comment by boskuv** [comment]
Possible solution: 

import sys
sys.setrecursionlimit(N+1), where N - lines in source file divided by linecount argument

**Comment by ram-jayapalan** [comment]
With the latest release, the splits are now generated using iterative approach rather than recursive approach that should solve this issue.
