### ISSUE TITLE
Feature request: zero padding file suffix number

### ISSUE THREAD

**Issue by alanraetz** [ram-jayapalan/filesplit#24]
Currently, listing and processing the directory with the split files appears like this, in alphabetical instead of numerical order (it would be a great option to be able to zero pad the number suffix): 
-a---l         1/14/2023   5:42 PM        6286741 fixedScanPeptides_SBS4_1.fasta
-a---l         1/14/2023   5:42 PM        6295491 fixedScanPeptides_SBS4_10.fasta
-a---l         1/14/2023   5:42 PM        6295240 fixedScanPeptides_SBS4_100.fasta
-a---l         1/14/2023   5:42 PM        6276446 fixedScanPeptides_SBS4_101.fasta
-a---l         1/14/2023   5:42 PM        6293260 fixedScanPeptides_SBS4_102.fasta
-a---l         1/14/2023   5:42 PM        6316025 fixedScanPeptides_SBS4_103.fasta
-a---l         1/14/2023   5:42 PM        6305043 fixedScanPeptides_SBS4_104.fasta
-a---l         1/14/2023   5:42 PM        6304395 fixedScanPeptides_SBS4_105.fasta
-a---l         1/14/2023   5:42 PM        6314575 fixedScanPeptides_SBS4_106.fasta
-a---l         1/14/2023   5:42 PM        6275732 fixedScanPeptides_SBS4_107.fasta
-a---l         1/14/2023   5:42 PM        6292125 fixedScanPeptides_SBS4_108.fasta
-a---l         1/14/2023   5:42 PM        3766451 fixedScanPeptides_SBS4_109.fasta
-a---l         1/14/2023   5:42 PM        6282594 fixedScanPeptides_SBS4_11.fasta
-a---l         1/14/2023   5:42 PM        6292344 fixedScanPeptides_SBS4_12.fasta
-a---l         1/14/2023   5:42 PM        6289697 fixedScanPeptides_SBS4_13.fasta
-a---l         1/14/2023   5:42 PM        6275150 fixedScanPeptides_SBS4_14.fasta
-a---l         1/14/2023   5:42 PM        6284864 fixedScanPeptides_SBS4_15.fasta
-a---l         1/14/2023   5:42 PM        6300151 fixedScanPeptides_SBS4_16.fasta
-a---l         1/14/2023   5:42 PM        6287493 fixedScanPeptides_SBS4_17.fasta
-a---l         1/14/2023   5:42 PM        6289600 fixedScanPeptides_SBS4_18.fasta
-a---l         1/14/2023   5:42 PM        6290117 fixedScanPeptides_SBS4_19.fasta
-a---l         1/14/2023   5:42 PM        6257899 fixedScanPeptides_SBS4_2.fasta
-a---l         1/14/2023   5:42 PM        6305684 fixedScanPeptides_SBS4_20.fasta
(etc)

**Comment by jeremyis78** [comment]
@alanraetz, I created a PR to add your feature.  With this PR, it will add the zero padding so files will sort correctly.  

https://github.com/ram-jayapalan/filesplit/pull/30

A sample of how it would look with default settings with zero-padding:
ls -1 split_test
manifest
mergedfile.csv
test_0001.txt
test_0002.txt
test_0003.txt
test_0004.txt
test_0005.txt
test_0006.txt
test_0007.txt
test_0008.txt
test_0009.txt
test_0010.txt
test_0011.txt

**Comment by ram-jayapalan** [comment]
Thank you @jeremyis78 . I'll review and merge your PR.

**Comment by ram-jayapalan** [comment]
This feature is now available in the latest release
