### ISSUE TITLE
ypeError: Required argument 'name' (pos 1) not found

### ISSUE THREAD

**Issue by Vino-git** [ram-jayapalan/filesplit#4]
Please help on the below error. 

>>> for i in os.listdir('/directory/'):
...     if re.search('.txt',i):
...             fs = FileSplit(file="file.txt", splitsize=7000, output_dir='/path/to/directory/')
...             fs.split()
... 
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File ".local/lib/python2.7/site-packages/fsplit/filesplit.py", line 51, in split
    with open(file=self.file, mode="rb") as f:
TypeError: Required argument 'name' (pos 1) not found

**Comment by bwalrond** [comment]
Getting the same error

**Comment by ram-jayapalan** [comment]
Python 2.7 is no longer supported. The lib can only run on python 3. Apologies for any inconvenience.
