### ISSUE TITLE
Feature request: unsplit()

### ISSUE THREAD

**Issue by pranjalchaubey** [ram-jayapalan/filesplit#7]
Please have a function to put the split files back together into a single file as well. 
_unsplit()_ could be a nice name for such a function.

**Comment by marktodisco** [comment]
I agree with **pranjalchaubey**. Having an `unsplit()` function would be great! I don't know if I would be comfortable using the `split()` function without having an _internal_ way to undo the split.

**Comment by ram-jayapalan** [comment]
I had a different use case in mind when I wrote this but since I see different use cases now, it makes sense and I will consider this feature request on the next release.

**Comment by marktodisco** [comment]
@ram-jayapalan Sounds great! You may also want to check out the `pysplitter` package on PyPi. I needed an immediate solution, so built this tool inspired by your work.

**Comment by ram-jayapalan** [comment]
v3 has been released with file merge functionality. Check out the release notes. Thanks for the feedback and support.
