### ISSUE TITLE
filesplit Doesn't Work with Certain Chunk Sizes

### ISSUE THREAD

**Issue by hal9000-hub** [ram-jayapalan/filesplit#8]
Hi there,

I have a python script that uses filesplit to create chunks from a file and then upload those chunks onto a web server.

The size of my file is 9570 bytes. 

When I set my 'splitsize' to 3000, it will return 4 chunks, which is expected.

However, when I set my 'splitsize' to 2000 it will return  6 chunks, when I was expecting 5 chunks.

So when I upload the chunks, I upload the wrong number of chunks to the webserver.

Is there an issue or am I not using this library correctly.

Example of Code below:

```
#Split File into Chunks#
fs=FileSplit(file='File.xlsx', splitsize=3000)
fs.split()

#Check File Size#
size = os.stat('File.xlsx').st_size
print(size)

#Upload Chunks#
i=1
while i < math.ceil(size/3000)+1:

```
Warm Regards,

**Comment by ram-jayapalan** [comment]
Please try with the latest version v3 and let me know how it goes. By the way this new version is not backward compatible.
