### ISSUE TITLE
Issue with 'path/to/file' parameters

### ISSUE THREAD

**Issue by talktotyagi** [ram-jayapalan/filesplit#9]
Liked the functionality, but by accidentally I think found an issue.

I had a file named: net1.dat in the folder c:\temp\filesplit
and for output I created new folder: new_files

so when I create an instance using:
fs = FileSplit(file='C:\Temp\filesplit\new1.dat', splitsize=1000000000, output_dir='C:\Temp\filesplit\new_files')

I get the error saying file not found.

>>> fs = FileSplit(file='C:\Temp\filesplit\new1.dat', splitsize=1000000000, output_dir='C:\Temp\filesplit\new_files')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\axt405\AppData\Local\Programs\Python\Python37\lib\site-packages\fsplit\filesplit.py", line 24, in __init__
    raise FileNotFoundError("The given file path '{0}' is not valid".format(file))
FileNotFoundError: The given file path 'C:\Tempilesplit
ew1.dat' is not valid
>>>

when I closely looked, I realized that even in the file names and poutput directory if there is any occurence of "\n", it treats them as new line char and then throws the error.

I changed the folder name and file name so they don't start with n and it worked as expected.

another thought, what if there is any "\n" in the data? Not sure how this would behave.

**Comment by ram-jayapalan** [comment]
Hi there,
I see from the error msg that it's complaining the file does not exist. When I closely looked into the args you are passing, I see you wanted to split net1.dat but in the file split function you have specified as new1.dat. That's the reason you are getting that error msg. Please try specifying the right path/name.
